=== jochenw/icm/icm-parent/icm-core/src/main/resources/com/github/jochenw/rcm/core/api/schema/icm-plugins.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://namespaces.github.com/jochenw/icm/icm-plugins/1.0.0" xmlns:tns="http://namespaces.github.com/jochenw/icm/icm-plugins/1.0.0" elementFormDefault="qualified">
  <xs:element name="icm-plugins">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="icm-plugin" minOccurs="1" maxOccurs="unbounded" type="tns:IcmPlugin"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="IcmPlugin">
    <xs:attribute name="class" type="xs:string" use="required"/>
  </xs:complexType>
</xs:schema>

=== jochenw/icm/icm-parent/icm-core/src/main/resources/META-INF/icm/icm-plugins.xml
<?xml version="1.0" encoding="UTF-8"?>
<icm-plugins xmlns="http://namespaces.github.com/jochenw/icm/icm-plugins/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://namespaces.github.com/jochenw/icm/icm-plugins/1.0.0 ../../com/github/jochenw/icm/core/api/schema/icm-plugins.xsd ">
  <icm-plugin class="com.github.jochenw.icm.core.impl.plugins.AnnotationBasedResourceInfoProvider"/>
  <icm-plugin class="com.github.jochenw.icm.core.impl.plugins.AnnotatedClassResourceInfoProvider"/>
  <icm-plugin class="com.github.jochenw.icm.core.api.plugins.SqlScriptChangeInstaller"/>
  <icm-plugin class="com.github.jochenw.icm.core.api.plugins.JdbcContextProvider"/>
  <icm-plugin class="com.github.jochenw.icm.core.impl.plugins.ClassExecutor"/>
  <icm-plugin class="com.github.jochenw.icm.core.api.plugins.ActiveMqAdministrationPlugin"/>
  <icm-plugin class="com.github.jochenw.icm.core.api.plugins.ActiveMqContextProvider"/>
  <icm-plugin class="com.github.jochenw.icm.core.api.plugins.GroovyScriptChangeInstaller"/>
  <icm-plugin class="com.github.jochenw.icm.core.api.plugins.TextFileEditingChangeInstaller"/>
  <icm-plugin class="com.github.jochenw.icm.core.impl.plugins.ExecChangeInstaller"/>
</icm-plugins>
